---
#cron-secret-scanning.yaml
name: Scheduled Secret Scan

on:
  schedule:
    - cron: "23 13 * * *"

permissions: read-all

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@30d5bb91af1a771378349dbbb0c82129392acf70 # v3.95.6
        with:
          extra_args: --results=verified,unknown
